version: "3.7"
services:
  db:
     image: postgres:12.1
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
     ports: 
       - '5432:5432'
     volumes:
       - rails-postgres:/var/lib/postgresql/data
  demo:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
        USER: "${USERNAME}"
    volumes:
      - rails-volume:/opt/rails_demo_app
    links:
      - db
    ports:
      - '8010:8010'
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - demo
    ports:
      - '80:80'
volumes:
  rails-volume:
  rails-postgres:
