FROM nginx:latest AS rails-nginx
COPY config/reverse-proxy.conf /etc/nginx/conf.d/reverse-proxy.conf
EXPOSE 80
STOPSIGNAL SIGTERM
RUN rm /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]


