version: "3.7"
services:
  demo:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
        USER: "${USERNAME}"
    volumes:
      - rails_volume:/opt/rails_demo_app
    ports:
      - '8010:8010'
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - demo
    ports:
      - '80:80'
volumes:
  rails_volume:
